"""
Converts all-MiniLM-L6-v2 to Core ML for on-device query embedding.

Two things make this conversion non-obvious:

1. Mean-pooling and L2 normalization are baked into the traced graph. The model's
   single output is a ready-to-use 384-float unit vector, so Swift never touches
   a tensor. This isn't just convenience — pooling is the easiest place to
   silently diverge from the corpus embeddings, and baking it in means there is
   only one implementation of it, validated here.

2. Enumerated input shapes rather than a single fixed length. Queries are short;
   padding every one to 256 tokens would waste most of the compute. Enumerated
   shapes stay Neural Engine-friendly in a way RangeDim does not.

The corpus embeddings were generated by Transformers.js
(apps/web/scripts/build-embeddings-convex.ts) from Xenova/all-MiniLM-L6-v2,
which is a straight ONNX export of the sentence-transformers checkpoint loaded
here — same weights. The validation step below proves that end to end by
re-embedding the golden queries and comparing against the vectors Transformers.js
produced for them.
"""

from __future__ import annotations

import json
import pathlib
import shutil
import sys

import numpy as np
import torch
import torch.nn as nn
import coremltools as ct
from transformers import AutoModel, AutoTokenizer

MODEL_ID = "sentence-transformers/all-MiniLM-L6-v2"
DIM = 384
SEQ_LENGTHS = [32, 64, 128, 256]
DEFAULT_SEQ = 128
COSINE_THRESHOLD = 0.999

PIPELINE_ROOT = pathlib.Path(__file__).resolve().parent.parent
REPO_ROOT = PIPELINE_ROOT.parent.parent
OUT_DIR = PIPELINE_ROOT / "out"
GOLDEN = REPO_ROOT / "apps/ios/HadithKit/Tests/HadithKitTests/Resources/golden.json"


class PooledEmbedder(nn.Module):
    """MiniLM + attention-masked mean pooling + L2 norm, as one graph."""

    def __init__(self, encoder: nn.Module):
        super().__init__()
        self.encoder = encoder

    def forward(self, input_ids: torch.Tensor, attention_mask: torch.Tensor):
        hidden = self.encoder(input_ids=input_ids, attention_mask=attention_mask)[0]
        mask = attention_mask.unsqueeze(-1).to(hidden.dtype)
        summed = (hidden * mask).sum(dim=1)
        # clamp mirrors sentence-transformers' pooling: an all-zero mask would
        # otherwise divide by zero rather than yield a zero vector.
        counts = mask.sum(dim=1).clamp(min=1e-9)
        pooled = summed / counts
        return pooled / pooled.norm(p=2, dim=1, keepdim=True).clamp(min=1e-12)


def build_mlpackage(model: PooledEmbedder, tokenizer) -> pathlib.Path:
    example = tokenizer(
        "example query text",
        return_tensors="pt",
        padding="max_length",
        truncation=True,
        max_length=DEFAULT_SEQ,
    )
    example_ids = example["input_ids"].to(torch.int32)
    example_mask = example["attention_mask"].to(torch.int32)

    traced = torch.jit.trace(model, (example_ids, example_mask), strict=False)

    shapes = ct.EnumeratedShapes(
        shapes=[[1, n] for n in SEQ_LENGTHS],
        default=[1, DEFAULT_SEQ],
    )

    mlmodel = ct.convert(
        traced,
        inputs=[
            ct.TensorType(name="input_ids", shape=shapes, dtype=np.int32),
            ct.TensorType(name="attention_mask", shape=shapes, dtype=np.int32),
        ],
        outputs=[ct.TensorType(name="embedding", dtype=np.float32)],
        minimum_deployment_target=ct.target.iOS18,
        compute_precision=ct.precision.FLOAT16,
        compute_units=ct.ComputeUnit.ALL,
        convert_to="mlprogram",
    )

    mlmodel.short_description = (
        "all-MiniLM-L6-v2 sentence embedder. Output is a 384-dim L2-normalized "
        "vector; mean pooling and normalization are inside the graph."
    )
    mlmodel.input_description["input_ids"] = "BERT WordPiece token ids, right-padded"
    mlmodel.input_description["attention_mask"] = "1 for real tokens, 0 for padding"
    mlmodel.output_description["embedding"] = "384-dim unit vector"

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    path = OUT_DIR / "MiniLM.mlpackage"
    if path.exists():
        shutil.rmtree(path)
    mlmodel.save(str(path))
    return path


def pick_length(token_count: int) -> int:
    for n in SEQ_LENGTHS:
        if token_count <= n:
            return n
    return SEQ_LENGTHS[-1]


def validate(path: pathlib.Path, tokenizer) -> None:
    """Re-embed the golden queries and compare against the Transformers.js vectors."""
    if not GOLDEN.exists():
        print(f"! {GOLDEN} not found — skipping validation.", file=sys.stderr)
        print("  Run `npm run capture-golden -w @check-the-chain/pipeline` first.", file=sys.stderr)
        return

    cases = json.loads(GOLDEN.read_text())["cases"]
    mlmodel = ct.models.MLModel(str(path))

    worst = 1.0
    worst_query = ""
    for case in cases:
        raw = tokenizer(case["query"], truncation=True, max_length=SEQ_LENGTHS[-1])
        seq = pick_length(len(raw["input_ids"]))
        enc = tokenizer(
            case["query"],
            return_tensors="np",
            padding="max_length",
            truncation=True,
            max_length=seq,
        )
        out = mlmodel.predict(
            {
                "input_ids": enc["input_ids"].astype(np.int32),
                "attention_mask": enc["attention_mask"].astype(np.int32),
            }
        )["embedding"].reshape(-1)[:DIM]

        reference = np.asarray(case["embedding"], dtype=np.float32)
        cosine = float(np.dot(out, reference))
        if cosine < worst:
            worst, worst_query = cosine, case["query"]

    print(f"  worst cosine vs Transformers.js: {worst:.6f}  ({worst_query!r})")
    if worst < COSINE_THRESHOLD:
        raise SystemExit(
            f"Core ML embeddings diverge from the corpus embeddings "
            f"({worst:.6f} < {COSINE_THRESHOLD}). Semantic search would return "
            f"different results on iOS than on web. Check tokenization and pooling."
        )


def export_tokenizer(tokenizer) -> None:
    """
    Emits vocab.txt for HadithKit's BertTokenizer.

    One line per token, ordered by id — the same format the original BERT
    release used, and all a WordPiece implementation needs. The tokenizer is
    plain BERT-uncased (BertNormalizer with lowercase and accent stripping,
    BertPreTokenizer, WordPiece with a '##' continuation prefix), which is why
    HadithKit implements it directly instead of taking a dependency.
    """
    vocab = tokenizer.get_vocab()
    ordered = [""] * (max(vocab.values()) + 1)
    for token, idx in vocab.items():
        ordered[idx] = token

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    dest = OUT_DIR / "vocab.txt"
    dest.write_text("\n".join(ordered), encoding="utf-8")
    print(f"  {dest.relative_to(REPO_ROOT)}  {len(ordered)} tokens")

    # Sanity-check the invariants BertTokenizer.swift hard-codes.
    expected = {"[PAD]": 0, "[UNK]": 100, "[CLS]": 101, "[SEP]": 102}
    for token, idx in expected.items():
        if vocab.get(token) != idx:
            raise SystemExit(
                f"Special token {token} moved to id {vocab.get(token)} (expected {idx}). "
                f"Update BertTokenizer.swift."
            )


def main() -> None:
    print(f"Loading {MODEL_ID}...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    encoder = AutoModel.from_pretrained(MODEL_ID).eval()
    model = PooledEmbedder(encoder).eval()

    print("Tracing and converting to Core ML...")
    with torch.no_grad():
        path = build_mlpackage(model, tokenizer)

    size_mb = sum(f.stat().st_size for f in path.rglob("*") if f.is_file()) / 1e6
    print(f"  {path.relative_to(REPO_ROOT)}  {size_mb:.1f} MB")

    export_tokenizer(tokenizer)

    print("Validating against golden query embeddings...")
    validate(path, tokenizer)
    print("\nCore ML model ready.")


if __name__ == "__main__":
    main()
